# Generated by Django 5.0.1 on 2024-01-20 17:35

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blockedsite_sitevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='end_date',
            field=api.models.DateTimeWithoutTZField(),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='start_date',
            field=api.models.DateTimeWithoutTZField(),
        ),
    ]
