# Generated by Django 5.0.1 on 2024-01-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sitevisit_end_date_alter_sitevisit_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedsite',
            name='blocked_count',
            field=models.IntegerField(default=0),
        ),
    ]
