# Generated by Django 5.0.1 on 2024-01-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blockedsite_blocked_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedsite',
            name='site_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='site_url',
            field=models.CharField(max_length=255),
        ),
    ]
