# Generated by Django 5.0.1 on 2024-01-21 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_blockedsite_site_url_alter_sitevisit_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedsite',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
